// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoReleaseApi.Models;

#nullable disable

namespace PoReleaseApi.Migrations
{
    [DbContext(typeof(PoReleaseContext))]
    partial class PoReleaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PoReleaseApi.Models.PoRelease", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AdditionalNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("additionalNotes");

                    b.Property<string>("AreaManagerEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("areaManagerEmail");

                    b.Property<string>("Attachment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("attachment");

                    b.Property<string>("CancellationPolicy")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("CustomerCancellationTerms")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("customerCancellationTerms");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("customerName");

                    b.Property<string>("HighUrgency")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("highUrgency");

                    b.Property<bool?>("IsAvailableInCompany")
                        .HasColumnType("bit")
                        .HasColumnName("isAvailableInCompany");

                    b.Property<bool?>("IsCheckedDnowInventory")
                        .HasColumnType("bit")
                        .HasColumnName("isCheckedDnowInventory");

                    b.Property<bool?>("IsCollaborateWithCorporateAndCentral")
                        .HasColumnType("bit")
                        .HasColumnName("isCollaborateWIthCorporateAndCentral");

                    b.Property<bool?>("IsPoGreaterFiftyThousand")
                        .HasColumnType("bit")
                        .HasColumnName("isPoGreaterFiftyThousand");

                    b.Property<bool?>("IsUsesItemCodes")
                        .HasColumnType("bit")
                        .HasColumnName("isUsesItemCodes");

                    b.Property<string>("PoNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("poNumber");

                    b.Property<string>("PoType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("poType");

                    b.Property<string>("RequestReason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("requestReason");

                    b.Property<string>("RequestingPlant")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("requestingPlant");

                    b.Property<string>("RestockingFees")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("restockingFees");

                    b.Property<int?>("TotalPovalue")
                        .HasColumnType("int")
                        .HasColumnName("totalPOValue");

                    b.Property<string>("VendorName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("vendorName");

                    b.Property<string>("VendorReturnPolicy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("vendorReturnPolicy");

                    b.HasKey("Id");

                    b.ToTable("PoRelease", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
